name: Build and run tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install test dependencies
        run: |
          pip install -r test-requirements.txt
      - name: Install rmdex
        run: |
          pip install .
      - name: Run tests
        run: |
          pytest rmdex --log-level DEBUG --cov-config=.coveragerc --cov=rmdex
      - name: Collect code coverage data
        run: |
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: "d95d4b51-2a76-4fd8-a21f-6368e114e9ed"
